### ISSUE TITLE
Composer autoloading

### ISSUE THREAD

**Issue by aksalj** [AfricasTalkingLtd/africastalking-php#1]
Composer autoloading does not seem to be working:

```shell
composer require africastalking/africastalking
```
Then
```php
<?php
require 'vendor/autoload.php';

$gateway = new AfricasTalkingGateway($USERNAME, $API_KEY);
```
Throws

`Class 'AfricasTalkingGateway' not found in index.php`

Or am I doing something wrong?

**Comment by skedone** [comment]
Hi @aksalj, you are not doing anything wrong.
The problem is the library which has never been ported correctly to be used with an autoloader.

I have create a pull request for this #2 
Cheers.

**Comment by ianjuma** [comment]
Merged, sorry about the delay!
I will proceed an close this.
