### ISSUE TITLE
Can I make a PR to this repo?

### ISSUE THREAD

**Issue by mwakaambrose** [AfricasTalkingLtd/africastalking-php#18]
I would like a more fluent Api to this SDKs here is an example.
```php
 SMS::with('username', 'api_key'))
 ->to('recipient[s]')
 ->message('hello world')
 ->as('SENDER')
 ->asPremium()
 ->shouldEnqueue()
 ->addOtherOptions([options]);
 ->done()
```
I believe this is more clean and straight forward to get started with. This is just a sample. If you guys are open to it, I will be more than glad to provide more information.

**Comment by marvinhosea** [comment]
I think we should just make a whole new AT package

**Comment by r115** [comment]
Start one ... I'll join in

**Comment by mwakaambrose** [comment]
> I think we should just make a whole new AT package

Sounds good to me.

**Comment by AnthonyLimo** [comment]
Hey guys, you can definitely make a PR to the repo. Would be nice to see an update for the PHP library
