### ISSUE TITLE
sdk not compatible with guzzlehttp/guzzle 7.0.1

### ISSUE THREAD

**Issue by murethi** [AfricasTalkingLtd/africastalking-php#28]
Installation requires one to downgrade to guzzle 6.5.5 from later versions of guzzle

**Comment by marvinhosea** [comment]
This is has been fixed by this PR https://github.com/AfricasTalkingLtd/africastalking-php/pull/29#issue-487195848 waiting for it to be merged. I will try and reach out.

**Comment by marvinhosea** [comment]
This issue has been fixed on v3.0.0, update your package and @murethi you can close this issue
