### ISSUE TITLE
Naming warning when using Composer install for the example application

### ISSUE THREAD

**Issue by bkmgit** [AfricasTalkingLtd/africastalking-php#34]
Get warning message below:
Deprecation warning: Your package name africastalking-example is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$". Make sure you fix this as Composer 2.0 will error.

**Comment by muarachmann** [comment]
How are you trying to install @bkmgit . Are you doing a `composer require africastalking/africastalking`
