### ISSUE TITLE
Vendor file

### ISSUE THREAD

**Issue by c-annan** [AfricasTalkingLtd/africastalking-php#38]
Vendor folder is not a part of the repository and the SDK folders are not found

**Comment by SamuelMwangiW** [comment]
Hi @c-annan,

You are correct, the package does not ship the vendor folder and in most scenarios, neither should you.

The contents of the vendor folder is managed by `composer` package manager

To get started:

1. confirm that you have a `composer.json` in your project root, if not run `composer init` and follow prompts.
2. Install this package by running `composer require africastalking/africastalking`
3. build your application
