### ISSUE TITLE
php 8

### ISSUE THREAD

**Issue by Jammiel** [AfricasTalkingLtd/africastalking-php#47]
Problem 1
    - Root composer.json requires africastalking/africastalking ^2.4 -> satisfiable by africastalking/africastalking[v2.4.0].
    - africastalking/africastalking v2.4.0 requires guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
  Problem 2
    - league/glide 2.0.x-dev requires php ^5.4 | ^7.0 -> your php version (8.0.15) does not satisfy that requirement.
    - spatie/crawler 6.0.2 requires spatie/browsershot ^3.14 -> satisfiable by spatie/browsershot[3.57.5].
    - spatie/browsershot 3.57.5 requires spatie/image ^1.5.3|^2.0 -> satisfiable by spatie/image[2.0.0].
    - spatie/laravel-sitemap 5.9.2 requires spatie/crawler ^5.0|^6.0 -> satisfiable by spatie/crawler[6.0.2].
    - spatie/image 2.0.0 requires league/glide ^2.0 -> satisfiable by league/glide[2.0.x-dev].
    - spatie/laravel-sitemap is locked to version 5.9.2 and an update of this package was not requested.

**Comment by SamuelMwangiW** [comment]
@Jammiel kindly update `africastalking/africastalking` to `^3.0` and it should fix Problem 1. The second problem is not related to `africastalking/africastalking`

**Comment by Jammiel** [comment]
thanks so much, issue resolved
